spring.application.name=c4s

spring.datasource.url=jdbc:mysql://localhost:3306/c4s
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

cloudinary.cloud-name=m2wwiuic
cloudinary.api-key=352965851547711
cloudinary.api-secret=BQ6UYWwmYTWITb63t-brMlaJhnY
